import Head from "next/head";
import React from "react";
import Navbar from "./Navbar";
import Home from "../pages";
import Footer from "./Footer";
const Layout = ({ children }) => {
  return (
    <>
      <div className="layout">
        <Head>
          <title>Webshop by atiqulislamwb</title>
          <meta name="description" content="Generated by Next and Sanity" />
          <link rel="icon" href="./favicon.ico" />
        </Head>
        <header>
          <Navbar />
        </header>
        <main className="main-container ">{children}</main>
        <footer>
          <Footer />
        </footer>
      </div>
    </>
  );
};

export default Layout;
